GET http://localhost:8080/locations
Accept: application/json

###
GET http://localhost:8080/locations
Accept: application/xml

####

GET http://localhost:8080/locations/1
Accept: application/json

###
GET http://localhost:8080/locations/1
Accept: application/xml

###

POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Location - 5",
  "lat": 5.0,
  "lon": -5.0
}
### validáció

POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "hello",
  "lat": 91.0,
  "lon": 10
}

###
PUT http://localhost:8080/locations/1
Content-Type: application/json
Accept: application/json

{
  "name": "Location - 100",
  "lat": 5.0,
  "lon": -5.0
}
###
DELETE http://localhost:8080/locations/1
###
GET http://localhost:8080/locations/100
Accept: application/json
###
PUT http://localhost:8080/locations/100
Content-Type: application/json
Accept: application/json

{
  "name": "Location - 100",
  "lat": 5.0,
  "lon": -5.0
}

